[features]
seeds = false
[programs.localnet]
blob_metadata = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/sammyharris/.config/solana/id.json"

[workspace]
members = [
    "."
]

